name = "aawaz-cf"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWE1OWM1ODItOGRkYS00MmI5LTllZWUtZTk5ZTAxYzlhYjI1IiwidGVuYW50X2lkIjoiOTIxOTljMzI2MjU3NWM1ZWQwOWM3MWNkYjNmOThiN2M3NmRhOGU1Njk2NWMyMmIyMzg2YmQxMmMxY2E3NTkzOSIsImludGVybmFsX3NlY3JldCI6IjkyMjdkMjhhLWNjNmEtNGJhZS04MDhmLWNlMTQ0OGUzZGYxOCJ9.V3ZOY6Z6y-hgDnZs4Ni_-k3TQLdrjRStbWBDfXmLzY4"
JWT_SECRET = "navi1secret"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"